#! /bin/sh

# === Autostart === #
    # Hotkey daemon
    pgrep -x sxhkd > /dev/null || sxhkd &

    # Set default cursor
    xsetroot -cursor_name left_ptr & 

    # Bind keyboard layout change
    setxkbmap -layout 'us,ru' -variant ',,' -option 'grp:alt_shift_toggle'

    # Window compositor
    picom -b &

    # Bar
    ~/.config/bspwm/polybar.sh&

    # Autonaming desktops
    export PATH='/home/user/git/bspi':$PATH
    bspi_listen --config ${HOME}/.config/bspwm/bspi.ini &

    # Add swallowing feature
    export PATH='/home/user/git/bspswallow':$PATH
    pgrep bspswallow || bspswallow &

    # Set background
    feh --bg-fill ${HOME}/pictures/wallpapers/city.jpg &

    # Disable power saving
    xset s off -dpms &

    # Desktop notifications
    dbus-launch dunst --config ${HOME}/.config/dunst/dunstrc &

# Set workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# Set gaps
bspc config window_gap 10

# Set padding for bar
bspc config top_padding 30

# === Configurate borders === #
    # Width
    bspc config border_width 2

    # Colors
    bspc config focused_border_color \#AC3F48
    bspc config normal_border_color \#464345

# === Other settings === #
    bspc config split_ratio           0.52
    bspc config borderless_monocle    true
    bspc config gapless_monocle       true
    bspc config focus_follows_pointer true

# === Window settings === #
    bspc rule -a Pavucontrol state=floating
